### ISSUE TITLE
Error: Problem setting TLS options with MQTT

### ISSUE THREAD

**Issue by sabas1080** [intel-iot-devkit/aws-iot-intel#6]
Hi

I 'm trying to use intel MQTT in Edison

```
mosquitto_sub --cafile rootCA.pem --cert certs/cert.pem --key privateKey.pem -h g.internal.iot.us-east-1.amazonaws.com -p 8883 -q 1 -d -t $aws/things/Edison/shadow/update -i Edison
```
I have the next error with MQTT

```
Error: Problem setting TLS options. 
```

Thanks

**Comment by toddstavish** [comment]
Getting the same issue. Did you resolve it?

**Comment by w4ilun** [comment]
Hello,

The issue should be resolved once you upgrade the mosquitto client to 1.4.5, follow the instructions here:

https://software.intel.com/en-us/blogs/2015/02/20/building-and-running-mosquitto-mqtt-on-intel-edison

and replace the version with 1.4.5: http://mosquitto.org/files/source/mosquitto-1.4.5.tar.gz

Make sure you have all the dependencies installed as well (e.g. libuuid): http://sourceforge.net/projects/libuuid/files/latest/download

Check that you have successfully installed the latest mosquitto client by running:

mosquitto_pub --help | grep version

**Comment by mikekirkwood** [comment]
Was this confirmed?  When downloading Mosquitto 1.4.5 and compile it on Edison, it fails.  "recipe failed"

**Comment by dummy36** [comment]
how do I install libuuid dependencies. I am still getting Error: Problem setting TLS options.

**Comment by pdeolankar** [comment]
Hello,

I am trying to test connectivity from my raspberry pi device to the AWS IoT service using SSH,
command: 
mosquitto_pub --cafile ca.pem.crt --cert certificate.pem --key private_key.pem -h endpoint.us-west-2.amazonaws.com -p 8883 -q 1 -d -t topic1 -i temperature-1 -m "Helloooo"

and I get error as,
Error: Unable to load CA certificates, check cafile "ca.pem.crt"
Unable to connect (A TLS error occured)

my mosquitto client version is 1.4.10 
please share a solution...
